imports:
    - { resource: 'security.yml' }

parameters:

    # Locales
    routing_locales: '(fr|en)'
    enabled_locales: ['fr', 'en']
    default_locale: '%env(DEFAULT_LOCALE)%'

    # Webpack
    webpack_dev_server_base_url: '%env(WEBPACK_DEV_SERVER_BASE_URL)%'

    # Assets
    static_assets_base_path: 'assets' # corresponding to __STATIC_ASSETS_BASE_PATH__ value in webpack.config.js
    uploads_assets_base_path: 'uploads'

    # Application images
    application_images_webroot_relative_dir: '%uploads_assets_base_path%/application_images'
    application_images_dir: '%kernel.project_dir%/web/%application_images_webroot_relative_dir%'

    # session
    session_save_path: '%env(resolve:SESSION_SAVE_PATH)%'

    # Build
    builds_application_dir: '%env(resolve:BUILDS_APPLICATION_DIR)%'

    # API
    build_token_ttl: 600 # seconds

framework:
    translator:
        fallbacks: ['%default_locale%']
    default_locale: '%default_locale%'
    secret: '%env(SYMFONY_SECRET)%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: false }
    templating:
        engines: ['twig']
    trusted_hosts:   ~
    session:
        handler_id: 'session.handler.native_file'
        save_path: '%session_save_path%'
    fragments: ~
    http_method_override: true
    assets:
        packages:
            static:
                base_path: '%static_assets_base_path%'
    php_errors:
        log: true

twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - 'bootstrap_3_layout.html.twig'
    globals:
        timezone: '%env(TIMEZONE)%'
        application_images_webroot_relative_dir: '%application_images_webroot_relative_dir%'

doctrine:
    dbal:
        url: '%env(DB_URL)%'
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: 'doctrine.orm.naming_strategy.underscore'
        auto_mapping: true

swiftmailer:
    transport: '%env(MAILER_TRANSPORT)%'
    host: '%env(MAILER_HOST)%'
    username: '%env(MAILER_USER)%'
    password: '%env(MAILER_PASSWORD)%'
    spool: { type: 'memory' }

stof_doctrine_extensions:
    default_locale: '%default_locale%'
    orm:
        default:
            timestampable: true

lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_PRIVATE_KEY_PATH)%'
    public_key:  '%env(resolve:JWT_PUBLIC_KEY_PATH)%'
    pass_phrase:      '%env(JWT_KEY_PASS_PHRASE)%'
    token_ttl:        '%env(JWT_TOKEN_TTL)%'

bazinga_js_translation:
    active_locales: '%enabled_locales%'
    locale_fallback: '%default_locale%'
