<?php

namespace AppBuild\Bundle\ApplicationBundle\Entity;

/**
 * ApplicationRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationRepository extends \Doctrine\ORM\EntityRepository
{
}
